[Eth]
NetworkId = 12216
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 70000000
GasPrice = 100000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 100000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node.P2P]
MaxPeers = 200
ListenAddr = ":31398"

[Node.LogConfig]
FilePath = "l2p.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""

